"""add school code

Revision ID: 6d3ba94437e3
Revises: 3710a466d4b7
Create Date: 2026-08-26 09:31:59.388384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d3ba94437e3'
down_revision = '3710a466d4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_schools_code'), ['code'], unique=True)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable='False')
        batch_op.drop_index(batch_op.f('ix_teachers_employee_number'))
        batch_op.drop_column('employee_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', mysql.VARCHAR(length=30), nullable=False))
        batch_op.create_index(batch_op.f('ix_teachers_employee_number'), ['employee_number'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
