"""Add status to classrooms

Revision ID: d829eb3b89bb
Revises: 6d3ba94437e3
Create Date: 2026-08-30 16:48:59.077528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd829eb3b89bb'
down_revision = '6d3ba94437e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
